# Generated by Django 5.2 on 2025-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0002_rename_usercredits_usercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='tier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
