# Generated by Django 5.1.7 on 2025-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymenttransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
