# Generated by Django 5.2 on 2025-04-28 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0004_paymenttransaction_status'),
        ('payments', '0004_paymenttransaction_status_delete_usercredit'),
    ]

    operations = [
    ]
