# Generated by Django 5.1.7 on 2025-06-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_quickbookstoken_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickBooksToken',
        ),
    ]
