# Generated by Django 5.1.7 on 2025-07-26 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(help_text='Primary domain of the enterprise email', max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprise/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sso_enabled', models.BooleanField(default=False)),
                ('sso_metadata_url', models.URLField(blank=True, null=True)),
                ('sso_entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('require_domain_match', models.BooleanField(default=True, help_text='Require user emails to match the enterprise domain')),
            ],
            options={
                'verbose_name_plural': 'Enterprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('rookie', 'Rookie Enterprise Dashboard'), ('general', 'General Enterprise Dashboard')], default='general', max_length=10)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user can manage enterprise settings and users')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='enterprise.enterprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'enterprise')},
            },
        ),
    ]
