# Generated by Django 5.1.7 on 2025-07-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='sso_enabled',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='sso_entity_id',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='sso_metadata_url',
        ),
    ]
