# Generated by Django 5.1.7 on 2025-07-29 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_remove_enterprise_sso_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.CharField(choices=[('sport', 'Sport Enterprise'), ('general', 'General Enterprise')], default='sport', help_text='Type of enterprise', max_length=10),
        ),
        migrations.CreateModel(
            name='EnterpriseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(choices=[('media_training', 'Media Training'), ('coach', 'Coach'), ('gm', 'General Manager')], help_text='Vertical this question is associated with', max_length=20)),
                ('question_text', models.TextField(help_text='The actual question text')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Enterprise this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='enterprise.enterprise')),
            ],
            options={
                'verbose_name': 'Enterprise Question',
                'verbose_name_plural': 'Enterprise Questions',
                'ordering': ['enterprise', 'vertical', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('enterprise', 'vertical', 'question_text'), name='unique_question_per_enterprise_vertical')],
            },
        ),
    ]
