# Generated by Django 5.1.7 on 2025-07-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_enterprise_enterprise_type_enterprisequestion'),
    ]

    operations = [
    ]
