# Generated by Django 5.1.7 on 2025-07-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_set_default_enterprise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='position',
        ),
    ]
