# Generated by Django 5.1.7 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_remove_enterpriseuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisequestion',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL to the generated audio file in S3', max_length=500, null=True),
        ),
    ]
