# Generated by Django 5.1.7 on 2025-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_enterprisequestion_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisequestion',
            name='vertical',
            field=models.CharField(choices=[('media_training', 'Media Training'), ('coach', 'Coach'), ('gm', 'General Manager'), ('coaching', 'Coaching')], help_text='Vertical this question is associated with', max_length=20),
        ),
    ]
