# Generated by Django 5.1.7 on 2025-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_alter_enterprisequestion_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisequestion',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('nfl', 'NFL'), ('nba', 'NBA'), ('wnba', 'WNBA'), ('mlb', 'MLB')], help_text='Sport type this question is associated with (if applicable)', max_length=10, null=True),
        ),
    ]
