# Generated by Django 5.1.7 on 2025-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_enterprisequestion_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='accessible_verticals',
            field=models.JSONField(default=list, help_text='List of vertical IDs from RoomEnum that are accessible'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='one_on_one_coaching_link',
            field=models.URLField(blank=True, help_text='Link for 1-on-1 coaching booking', max_length=500, null=True),
        ),
    ]
