# Generated by Django 5.1.7 on 2025-08-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_enterprise_accessible_verticals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('presentation', 'Presentation'), ('pitch', 'Pitch'), ('public_speaking', 'Public Speaking'), ('media_training', 'Media Training'), ('coach', 'Coach'), ('general_manager', 'General Manager'), ('coaching', 'Coaching')], help_text='Type of room/vertical for this goal', max_length=20)),
                ('target_sessions', models.PositiveIntegerField(help_text='Target number of sessions to complete')),
                ('completed_sessions', models.PositiveIntegerField(default=0, help_text='Number of sessions completed so far')),
                ('due_date', models.DateField(blank=True, help_text='Optional due date for this goal', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Enterprise this goal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_goals', to='enterprise.enterprise')),
            ],
            options={
                'ordering': ['-is_active', 'due_date', 'room'],
                'unique_together': {('enterprise', 'room', 'is_active')},
            },
        ),
    ]
