# Generated by Django 5.1.7 on 2025-08-19 14:16

from django.db import migrations


def set_default_verticals(apps, schema_editor):
    """Set default verticals for existing enterprises"""
    Enterprise = apps.get_model('enterprise', 'Enterprise')
    
    # For sport enterprises
    sport_verticals = [
        'media_training',
        'coach',
        'gm',
        'pitch',
        'presentation',
        'public_speaking'
    ]
    
    # For general enterprises
    general_verticals = [
        'coaching',
        'pitch',
        'presentation',
        'public_speaking'
    ]
    
    # Update sport enterprises
    Enterprise.objects.filter(enterprise_type='sport').update(accessible_verticals=sport_verticals)
    
    # Update general enterprises
    Enterprise.objects.filter(enterprise_type='general').update(accessible_verticals=general_verticals)


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_traininggoal'),
    ]

    operations = [
        migrations.RunPython(set_default_verticals, reverse_code=migrations.RunPython.noop),
    ]
