# Generated by Django 5.1.7 on 2025-08-19 20:25

import django.core.validators
import enterprise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_update_enterprise_verticals'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload your favicon (ICO, PNG, or JPG)', null=True, upload_to='enterprise/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='primary_color',
            field=models.CharField(default='#262b3a', help_text='Primary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[enterprise.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='secondary_color',
            field=models.CharField(default='#10161e', help_text='Secondary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[enterprise.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='enterprisequestion',
            name='vertical',
            field=models.CharField(choices=[('media_training', 'Media Training'), ('coach', 'Coach'), ('gm', 'General Manager'), ('coaching', 'Coaching'), ('pitch', 'Pitch'), ('presentation', 'Presentation'), ('public_speaking', 'Public Speaking')], help_text='Vertical this question is associated with', max_length=20),
        ),
    ]
