# Generated by Django 5.1.7 on 2025-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_update_enterprise_verticals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisequestion',
            name='vertical',
            field=models.CharField(choices=[('media_training', 'Media Training'), ('coach', 'Coach'), ('gm', 'General Manager'), ('coaching', 'Coaching'), ('pitch', 'Pitch'), ('presentation', 'Presentation'), ('public_speaking', 'Public Speaking')], help_text='Vertical this question is associated with', max_length=20),
        ),
    ]
