# Generated by Django 5.1.7 on 2025-08-19 20:34

import django.core.validators
import enterprise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_enterprise_favicon_enterprise_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='favicon',
            field=models.ImageField(blank=True, help_text='User-specific favicon (overrides enterprise favicon if set)', null=True, upload_to='enterprise/user_branding/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='logo',
            field=models.ImageField(blank=True, help_text='User-specific logo (overrides enterprise logo if set)', null=True, upload_to='enterprise/user_branding/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='primary_color',
            field=models.CharField(blank=True, help_text='User-specific primary color (overrides enterprise color if set)', max_length=7, null=True, validators=[enterprise.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='User-specific secondary color (overrides enterprise color if set)', max_length=7, null=True, validators=[enterprise.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='user_type',
            field=models.CharField(choices=[('general', 'General User'), ('admin', 'Enterprise Admin')], default='general', max_length=10),
        ),
    ]
