# Generated by Django 5.1.7 on 2025-08-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_alter_enterprisequestion_vertical'),
        ('enterprise', '0013_enterpriseuser_favicon_enterpriseuser_logo_and_more'),
    ]

    operations = [
    ]
