# Generated by Django 5.1.7 on 2025-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_merge_20250820_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='coaching_sessions_booked',
            field=models.PositiveIntegerField(default=0, help_text='Number of coaching sessions booked through the one-on-one coaching link'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='one_on_one_coaching_link',
            field=models.URLField(blank=True, default=True, help_text='Link for 1-on-1 coaching booking', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='require_domain_match',
            field=models.BooleanField(default=False, help_text='Require user emails to match the enterprise domain'),
        ),
    ]
