# Generated by Django 5.1.7 on 2025-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0015_enterprise_coaching_sessions_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('nfl', 'NFL'), ('nba', 'NBA'), ('wnba', 'WNBA'), ('mlb', 'MLB')], help_text='Primary sport type for this enterprise (if applicable)', max_length=10, null=True),
        ),
    ]
