# Generated by Django 5.1.7 on 2025-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_enterprise_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='role',
            field=models.CharField(blank=True, help_text="User's role within the enterprise", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='team',
            field=models.CharField(blank=True, help_text="User's team within the enterprise", max_length=100, null=True),
        ),
    ]
