# Generated by Django 5.1.7 on 2025-08-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0017_enterpriseuser_role_enterpriseuser_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='secondary_color',
        ),
    ]
