# Generated by Django 5.1.7 on 2025-08-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0018_remove_enterpriseuser_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='require_domain_match',
        ),
    ]
