# Generated by Django 5.1.7 on 2025-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0019_remove_enterprise_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseuser',
            name='user_type',
            field=models.CharField(choices=[('standard', 'Standard User'), ('rookie_enterprise', 'Rookie Enterprise Dashboard'), ('general_enterprise', 'General Enterprise Dashboard')], default='general_enterprise', max_length=20),
        ),
    ]
