# Generated by Django 5.1.7 on 2025-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0020_alter_enterpriseuser_user_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enterprisequestion',
            name='unique_question_per_enterprise_vertical',
        ),
        migrations.AddField(
            model_name='enterprisequestion',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Neutral')], default='N', help_text='Gender for which this question is appropriate', max_length=1),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='user_type',
            field=models.CharField(choices=[('standard', 'Standard User'), ('rookie', 'Rookie Enterprise Dashboard'), ('general', 'General Enterprise Dashboard')], default='general', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='enterprisequestion',
            constraint=models.UniqueConstraint(fields=('enterprise', 'vertical', 'question_text', 'gender'), name='unique_question_per_enterprise_vertical_gender'),
        ),
    ]
