# Generated by Django 5.1.7 on 2025-09-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0021_remove_enterprisequestion_unique_question_per_enterprise_vertical_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininggoal',
            unique_together=set(),
        ),
    ]
