# Generated by Django 5.1.7 on 2025-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_available_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='available_credits',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Available credits on the user dashboard.', max_digits=10),
        ),
    ]
