# Generated by Django 5.1.7 on 2025-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_available_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='quickbooks_customer_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Media & Presentation', 'Media & Presentation'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Major League Sports', 'Major League Sports'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
