# Generated by Django 5.1.7 on 2025-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userprofile_quickbooks_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quickbooks_customer_id',
            field=models.CharField(blank=True, help_text='QuickBooks Customer ID linked to this user.', max_length=100, null=True, unique=True),
        ),
    ]
