# Generated by Django 5.1.7 on 2025-06-17 14:38

import django.core.validators
import users.models
import users.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_quickbooks_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload your favicon (ICO, PNG, or JPG)', null=True, storage=users.storages_backends.ProfilePicStorage(), upload_to='whitelabel/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your company logo (JPG, PNG, or SVG)', null=True, storage=users.storages_backends.ProfilePicStorage(), upload_to='whitelabel/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Primary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[users.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#000000', help_text='Secondary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[users.models.validate_hex_color]),
        ),
    ]
