# Generated by Django 5.1.7 on 2025-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_favicon_userprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_method',
            field=models.CharField(blank=True, choices=[('password', 'Password'), ('email_link', 'Email Link')], help_text='Last login method used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sso_code_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for the SSO login code', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sso_login_code',
            field=models.CharField(blank=True, help_text='One-time code for email login', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sso_login_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user can log in via email link (SSO)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('standard', 'Standard User'), ('rookie_enterprise', 'Rookie Enterprise Dashboard'), ('general_enterprise', 'General Enterprise Dashboard')], default='standard', help_text='Designates the type of user.', max_length=20),
        ),
    ]
