# Generated by Django 5.1.7 on 2025-08-04 14:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_last_login_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#262b3a', help_text='Primary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[users.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#10161e', help_text='Secondary brand color in hex format (e.g., #RRGGBB)', max_length=7, validators=[users.models.validate_hex_color]),
        ),
    ]
