# Generated by Django 5.1.7 on 2025-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_expiringtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_intent',
            field=models.CharField(blank=True, choices=[('early', 'Early Career Professional'), ('mid', 'Mid-level Professionals'), ('sales', 'Sales Professionals'), ('c_suite', 'C-suites'), ('entrepreneur', 'Entrepreneurs'), ('athlete', 'Major League Sports Athlete'), ('executive', 'Major League Sports Executive'), ('professional_organization', 'Professional Organization'), ('major_league_sports_athlete_executive', 'Major league sports athlete/executive')], help_text='Select your career/intention level at sign up.', max_length=50, null=True),
        ),
    ]
