# Generated by Django 5.1.7 on 2025-08-15 14:37

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def update_token_expirations(apps, schema_editor):
    ExpiringToken = apps.get_model('users', 'ExpiringToken')
    
    # Update all tokens to expire in 3 days from now
    ExpiringToken.objects.update(
        expires_at=timezone.now() + timedelta(days=3)
    )

def reverse_update(apps, schema_editor):
    # No need to do anything special to reverse this
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0024_transfer_tokens'),
    ]

    operations = [
        migrations.RunPython(update_token_expirations, reverse_update),
    ]
