# Generated by Django 5.1.7 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userprofile_user_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='available_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Available credits on the user dashboard.', max_digits=10),
        ),
    ]
