# Generated by Django 5.1.6 on 2025-03-23 16:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSequence',
            fields=[
                ('sequence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sequences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('pitch', 'Pitch Practice'), ('public', 'Public Speaking'), ('presentation', 'Presentation')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(help_text='Duration of the session')),
                ('note', models.TextField(blank=True, help_text='Optional note (for users)', null=True)),
                ('pauses', models.IntegerField(default=0)),
                ('emotional_expression', models.TextField(blank=True, null=True)),
                ('tone', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('audience_engagement', models.TextField(blank=True, null=True)),
                ('transformative_potential', models.TextField(blank=True, null=True)),
                ('visual_communication', models.TextField(blank=True, null=True)),
                ('total_time_saved', models.IntegerField(default=0)),
                ('slide_specific_timing', models.JSONField(blank=True, default=dict, null=True)),
                ('slides', models.FileField(blank=True, help_text='Optional slides for the session', null=True, upload_to='session_slides/%Y/%m/%d/')),
                ('virtual_environment', models.CharField(blank=True, choices=[('conference_room', 'Conference Room'), ('seminar_room', 'Seminar Room')], help_text='Select a virtual environment.', max_length=50, null=True)),
                ('allow_ai_questions', models.BooleanField(default=False, help_text='Allow AI to ask random questions during the session')),
                ('sequence', models.ForeignKey(blank=True, help_text='Optional sequence this session belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='practice_sessions.practicesequence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time of the chunk in the session (in seconds)')),
                ('end_time', models.FloatField(help_text='End time of the chunk in the session (in seconds)')),
                ('video_file', models.FileField(blank=True, help_text='Video file for this chunk', null=True, upload_to='session_chunks/%Y/%m/%d/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='practice_sessions.practicesession')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkSentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.PositiveIntegerField(default=0, help_text='Engagement Heatmap', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('audience_emotion', models.PositiveIntegerField(default=0, help_text='Audience Emotion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conviction', models.PositiveIntegerField(default=0, help_text='Convictions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clarity', models.PositiveIntegerField(default=0, help_text='Clarity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impact', models.PositiveIntegerField(default=0, help_text='impact', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('brevity', models.PositiveIntegerField(default=0, help_text='Brevity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('transformative_potential', models.PositiveIntegerField(default=0, help_text='transformative potential', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('body_posture', models.PositiveIntegerField(default=0, help_text='Body posture', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('general_feedback_summary', models.TextField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, help_text='Volume', null=True)),
                ('pitch_variability', models.FloatField(blank=True, help_text='Pitch variability', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Pace', null=True)),
                ('chunk_transcript', models.TextField(blank=True, help_text='Transcript', null=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='practice_sessions.sessionchunk')),
            ],
        ),
    ]
