# Generated by Django 5.1.7 on 2025-04-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='body_posture',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='engagement',
        ),
    ]
