# Generated by Django 5.1.6 on 2025-03-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='audience_engagement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='content_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='emotional_expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='emotional_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='pauses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='slide_specific_timing',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='tone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='total_time_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='transformative_potential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='visual_communication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
