# Generated by Django 5.1.6 on 2025-03-23 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='chunksentimentanalysis',
        #     old_name='area_of_improvement',
        #     new_name='general_feedback_summary',
        # ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='back_feedback',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='bad_back_time',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='bad_neck_time',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='curiosity',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='empathy',
        ),
        # migrations.RemoveField(
        #     model_name='chunksentimentanalysis',
        #     name='general_feedback',
        # ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='good_back_time',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='good_neck_time',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='mean_back_inclination',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='mean_neck_inclination',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='neck_feedback',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='range_back_inclination',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='range_neck_inclination',
        ),
        # migrations.RemoveField(
        #     model_name='chunksentimentanalysis',
        #     name='strengths',
        # ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='tone',
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='audience_emotion',
            field=models.PositiveIntegerField(default=0, help_text='Audience Emotion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='brevity',
            field=models.PositiveIntegerField(default=0, help_text='Brevity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='body_posture',
            field=models.PositiveIntegerField(default=0, help_text='Body posture', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='clarity',
            field=models.PositiveIntegerField(default=0, help_text='Clarity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='conviction',
            field=models.PositiveIntegerField(default=0, help_text='Convictions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='impact',
            field=models.PositiveIntegerField(default=0, help_text='impact', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='pace',
            field=models.FloatField(blank=True, help_text='Pace', null=True),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='volume',
            field=models.FloatField(blank=True, help_text='Volume', null=True),
        ),
    ]
