# Generated by Django 5.1.7 on 2025-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0002_remove_chunksentimentanalysis_body_posture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='slides_URL',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, storage='SlidesStorage', upload_to='session_slides/'),
        ),
    ]
