# Generated by Django 5.1.6 on 2025-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0002_practicesession_audience_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='slides',
            field=models.FileField(blank=True, help_text='Optional slides for the session', null=True, upload_to='session_slides/%Y/%m/%d/'),
        ),
    ]
