# Generated by Django 5.1.7 on 2025-04-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0002_alter_practicesession_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionchunk',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sessionchunk',
            name='start_time',
        ),
    ]
