# Generated by Django 5.1.7 on 2025-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0002_slidepreview_practicesession_slide_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='scheduled_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
