# Generated by Django 5.1.7 on 2025-04-20 22:53

import django.core.validators
import users.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0003_remove_practicesession_slides_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='pauses',
            field=models.IntegerField(default=0, help_text='Pause score for this chunk (expected over 100)'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='pauses',
            field=models.IntegerField(default=0, help_text='Average pause score for the session (expected over 100)'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, storage=users.storages_backends.SlidesStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp', 'key', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='vocal_variety',
            field=models.FloatField(default=0, help_text='Average of volume, pitch, pace, and pauses (expected over 100)'),
        ),
    ]
