# Generated by Django 5.1.7 on 2025-06-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0003_practicesession_scheduled_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='session_type',
            field=models.CharField(choices=[('pitch', 'Pitch Practice'), ('public', 'Public Speaking'), ('presentation', 'Presentation'), ('enterprise', 'Enterprise Specialty')], max_length=20),
        ),
        migrations.CreateModel(
            name='EnterpriseSpecialtySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_type', models.CharField(choices=[('rookie', 'Rookie'), ('pharmahq', 'PharmaHQ')], default='rookie', max_length=20)),
                ('rookie_type', models.CharField(blank=True, choices=[('media_training', 'Media Training'), ('speaking', 'Speaking')], max_length=20, null=True)),
                ('sport_type', models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('swimming', 'Swimming'), ('table_tennis', 'Table Tennis'), ('boxing', 'Boxing'), ('long_tennis', 'Long Tennis')], help_text='Sport type for the session (applicable for Media Training)', max_length=20, null=True)),
                ('speaker_notes', models.TextField(blank=True, help_text='Speaker notes for the session', null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_settings', to='practice_sessions.practicesession')),
            ],
        ),
    ]
