# Generated by Django 5.1.6 on 2025-03-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0003_practicesession_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='slide_specific_timing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
