# Generated by Django 5.1.7 on 2025-04-21 02:15

import django.core.validators
import users.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0004_alter_chunksentimentanalysis_pauses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, storage=users.storages_backends.SlidesStorage(), upload_to='slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp', 'key', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
