# Generated by Django 5.2 on 2025-04-23 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0004_alter_chunksentimentanalysis_pauses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='gestures_score_for_body_language',
            field=models.IntegerField(default=0, help_text='Score for gestures in body language analysis', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp', 'key', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
