# Generated by Django 5.1.7 on 2025-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0004_alter_practicesession_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisespecialtysession',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('swimming', 'Swimming'), ('table_tennis', 'Table Tennis'), ('boxing', 'Boxing'), ('tennis', 'Tennis'), ('hockey', 'Hockey'), ('soccer', 'Soccer'), ('baseball', 'Baseball')], help_text='Sport type for the session (applicable for Media Training)', max_length=20, null=True),
        ),
    ]
