# Generated by Django 5.1.7 on 2025-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0004_alter_sessionchunk_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionchunk',
            name='end_time',
            field=models.FloatField(blank=True, help_text='End time of the chunk in the session (in seconds)', null=True),
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='start_time',
            field=models.FloatField(blank=True, help_text='Start time of the chunk in the session (in seconds)', null=True),
        ),
    ]
