# Generated by Django 5.1.7 on 2025-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0005_sessionchunk_end_time_sessionchunk_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='audience_emotion',
            field=models.CharField(blank=True, help_text='Audience Emotion', max_length=50, null=True),
        ),
    ]
