# Generated by Django 5.1.7 on 2025-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0005_alter_enterprisespecialtysession_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisespecialtysession',
            name='rookie_type',
            field=models.CharField(blank=True, choices=[('media_training', 'Media Training'), ('speaking', 'Speaking'), ('coach', 'Coach'), ('gm', 'GM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='virtual_environment',
            field=models.CharField(blank=True, choices=[('conference_room', 'Conference Room'), ('board_room_1', 'Board Room 1'), ('board_room_2', 'Board Room 2'), ('pitch_studio', 'pitch_studio'), ('nba_room', 'NBA Room'), ('wnba_room', 'WNBA Room'), ('nfl_room', 'NFL Room'), ('mlb_room', 'MLB Room')], help_text='Select a virtual environment.', max_length=50, null=True),
        ),
    ]
