# Generated by Django 5.1.6 on 2025-03-19 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0005_sessionchunk_chunksentimentanalysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='allow_ai_questions',
            field=models.BooleanField(default=False, help_text='Allow AI to ask random questions during the session'),
        ),
        migrations.CreateModel(
            name='PracticeSequence',
            fields=[
                ('sequence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sequences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='practicesession',
            name='sequence',
            field=models.ForeignKey(blank=True, help_text='Optional sequence this session belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='practice_sessions.practicesequence'),
        ),
    ]
