# Generated by Django 5.1.7 on 2025-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0005_alter_practicesession_slides_file'),
        ('practice_sessions', '0005_practicesession_gestures_score_for_body_language_and_more'),
    ]

    operations = [
    ]
