# Generated by Django 5.1.7 on 2025-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_merge_20250423_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='slide_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='text_economy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='visual_communication',
            field=models.FloatField(default=0),
        ),
    ]
