# Generated by Django 5.1.6 on 2025-03-20 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_practicesession_allow_ai_questions_practicesequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='pause_metric_rationale',
            new_name='area_of_improvement',
        ),
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='body_language',
            new_name='body_posture',
        ),
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='convictions',
            new_name='conviction',
        ),
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='pitch_variability_rationale',
            new_name='general_feedback',
        ),
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='speaking_rate',
            new_name='pace',
        ),
        migrations.RenameField(
            model_name='chunksentimentanalysis',
            old_name='speaking_rate_rationale',
            new_name='strengths',
        ),
        migrations.RenameField(
            model_name='practicesession',
            old_name='content_organization',
            new_name='impact',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='appropriate_pauses',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='authenticity',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='dynamism',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='emotional_impact',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='eye_contact',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='filler_words',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='gestures',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='long_pauses',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='pacing',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='pauses_score',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='pitch_variability_score',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='speech_rate_score',
        ),
        migrations.RemoveField(
            model_name='chunksentimentanalysis',
            name='volume_score',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='emotional_impact',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='pronunciation',
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='chunk_transcript',
            field=models.TextField(blank=True, help_text='Transcript', null=True),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='impact',
            field=models.PositiveIntegerField(default=0, help_text='overall performance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='transformative_potential',
            field=models.PositiveIntegerField(default=0, help_text='transformative potential', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chunksentimentanalysis',
            name='engagement',
            field=models.PositiveIntegerField(default=0, help_text='Engagement Heatmap', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
