# Generated by Django 5.1.7 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_alter_chunksentimentanalysis_audience_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='goals',
            field=models.TextField(blank=True, default='Just practicing', null=True),
        ),
    ]
