# Generated by Django 5.1.7 on 2025-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_alter_chunksentimentanalysis_audience_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='goals',
            field=models.TextField(blank=True, default='Just practicing', null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='virtual_environment',
            field=models.CharField(blank=True, choices=[('conference_room', 'Conference Room'), ('seminar_room', 'Seminar Room'), ('board_room_1', 'Board Room 1'), ('board_room_2', 'Board Room 2')], help_text='Select a virtual environment.', max_length=50, null=True),
        ),
    ]
