# Generated by Django 5.1.7 on 2025-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_alter_enterprisespecialtysession_rookie_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisespecialtysession',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('nfl', 'NFL'), ('nba', 'NBA'), ('wnba', 'WNBA'), ('mlb', 'MLB')], help_text='Sport type for the session (applicable for Media Training)', max_length=20, null=True),
        ),
    ]
