# Generated by Django 5.1.7 on 2025-04-26 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0006_merge_20250423_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionchunk',
            options={'ordering': ['chunk_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='audio_path',
            field=models.CharField(blank=True, help_text='Path to the audio file for this chunk', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='chunk_number',
            field=models.IntegerField(blank=True, help_text='Order of the chunk in the session', null=True),
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this chunk was created'),
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='transcript',
            field=models.TextField(blank=True, help_text='Transcript of this chunk', null=True),
        ),
        migrations.AddField(
            model_name='sessionchunk',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this chunk was last updated'),
        ),
    ]
