# Generated by Django 5.1.7 on 2025-04-14 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0007_practicesession_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='filler_words',
            field=models.IntegerField(default=0, help_text='Number of filler words used'),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='gestures',
            field=models.BooleanField(default=False, help_text='Presence of positive gestures'),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='grammar',
            field=models.IntegerField(default=0, help_text='Grammar score or number of errors'),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='motion',
            field=models.IntegerField(default=0, help_text='Motion score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='posture',
            field=models.IntegerField(default=0, help_text='Posture score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='chunksentimentanalysis',
            name='trigger_response',
            field=models.IntegerField(default=0, help_text='Number of trigger responses detected'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='filler_words',
            field=models.IntegerField(default=0, help_text='Total filler words used in the session'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='gestures',
            field=models.BooleanField(default=False, help_text='Presence of positive gestures in the session'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='grammar',
            field=models.IntegerField(default=0, help_text='Overall grammar score or number of errors in the session'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='motion',
            field=models.IntegerField(default=0, help_text='Overall motion score for the session', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='posture',
            field=models.IntegerField(default=0, help_text='Overall posture score for the session', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='trigger_response',
            field=models.IntegerField(default=0, help_text='Total trigger responses detected in the session'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='goals',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='virtual_environment',
            field=models.CharField(blank=True, choices=[('conference_room', 'Conference Room'), ('board_room_1', 'Board Room 1'), ('board_room_2', 'Board Room 2')], help_text='Select a virtual environment.', max_length=50, null=True),
        ),
    ]
