# Generated by Django 5.2 on 2025-04-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0007_alter_sessionchunk_options_sessionchunk_audio_path_and_more'),
        ('practice_sessions', '0007_practicesession_slide_efficiency_and_more'),
    ]

    operations = [
    ]
