# Generated by Django 5.2 on 2025-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0007_alter_enterprisespecialtysession_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='session_type',
            field=models.CharField(choices=[('pitch', 'Pitch Practice'), ('public', 'Public Speaking'), ('presentation', 'Presentation'), ('enterprise', 'Rookie')], max_length=20),
        ),
    ]
