# Generated by Django 5.1.7 on 2025-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0008_chunksentimentanalysis_filler_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='goals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
