# Generated by Django 5.1.7 on 2025-08-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0008_alter_practicesession_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='slides_file',
        ),
    ]
