# Generated by Django 5.1.7 on 2025-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0009_remove_practicesession_slides_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisespecialtysession',
            name='enterprise_type',
            field=models.CharField(choices=[('rookie', 'Rookie'), ('pharmahq', 'PharmaHQ'), ('coaching', 'Coaching')], default='rookie', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='session_type',
            field=models.CharField(choices=[('pitch', 'Pitch Practice'), ('public', 'Public Speaking'), ('presentation', 'Presentation'), ('enterprise', 'Enterprise')], max_length=20),
        ),
    ]
