# Generated by Django 5.1.7 on 2025-04-27 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0009_alter_practicesession_slides_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicesession',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
