# Generated by Django 5.1.7 on 2025-04-27 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0011_alter_practicesession_slides_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, upload_to='slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp', 'key', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='virtual_environment',
            field=models.CharField(blank=True, choices=[('conference_room', 'Conference Room'), ('board_room_1', 'Board Room 1'), ('board_room_2', 'Board Room 2'), ('pitch_studio', 'pitch_studio')], help_text='Select a virtual environment.', max_length=50, null=True),
        ),
    ]
