# Generated by Django 5.1.7 on 2025-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0013_alter_practicesession_slides_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='compiled_video_url',
            field=models.URLField(blank=True, help_text='URL of the final compiled video for the session.', max_length=400, null=True),
        ),
    ]
