# Generated by Django 5.2 on 2025-04-30 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0014_practicesession_compiled_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='compiled_video_url',
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (e.g., PDF, PPT, image files).', null=True, upload_to='slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'odp', 'key', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
